language: java
jdk:
  - oraclejdk7
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
after_success:
  - echo "<settings><servers><server><id>oss-jfrog-artifactory</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASS}</password></server></servers></settings>" > ~/settings.xml
  - mvn deploy --settings ~/settings.xml
